//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqClient
    {
        public int RequestID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> MasterID { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Users Users { get; set; }
    }
}
